import Head from "next/head";

export default function Layout({ children }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=" h-24 border-b-[1px] border-gray-200 mx-24"></div>
        <div>{children}</div>
      </main>
    </>
  );
}
