import Head from "next/head";
import { useRouter } from "next/router";

export default function Layout({ children }: any) {
  const router = useRouter();
  const gotoHome = () => {
    router.push("/");
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <img
          src="/logo.png"
          alt="ha kin"
          className="h-24 pt-5 ml-24 cursor-pointer"
          onClick={gotoHome}
        />
        <div className="border-b-[1px] border-gray-200 mx-40"></div>
        <div className="pb-5">{children}</div>
      </main>
    </>
  );
}
