import Head from "next/head";
import { useRouter } from "next/router";
import { useAuth } from "../contexts/auth";

export default function Layout({ children }: any) {
  const router = useRouter();
  const auth = useAuth();
  const gotoHome = () => {
    router.push("/");
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className="flex justify-between items-center"
          style={{ paddingLeft: "6rem", paddingRight: "6rem" }}
        >
          <img
            src="/logo.png"
            alt="ha kin"
            className="cursor-pointer"
            style={{ height: "6rem", paddingTop: "1.25rem" }}
            onClick={gotoHome}
          />
          <div>
            <button
              className="border-2 rounded-md border-red-600"
              style={{ paddingLeft: "0.25rem", paddingRight: "0.25rem" }}
              onClick={() => auth.logout()}
            >
              Logout
            </button>
          </div>
        </div>
        <div className="border-b-[1px] border-gray-200 mx-40"></div>
        <div className="pb-5">{children}</div>
      </main>
    </>
  );
}
